# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mqeq.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 701)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.map_index_ledit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_index_ledit.sizePolicy().hasHeightForWidth())
        self.map_index_ledit.setSizePolicy(sizePolicy)
        self.map_index_ledit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.map_index_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.map_index_ledit.setObjectName("map_index_ledit")
        self.gridLayout.addWidget(self.map_index_ledit, 0, 1, 1, 1)
        self.map_subindex_ledit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_subindex_ledit.sizePolicy().hasHeightForWidth())
        self.map_subindex_ledit.setSizePolicy(sizePolicy)
        self.map_subindex_ledit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.map_subindex_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.map_subindex_ledit.setObjectName("map_subindex_ledit")
        self.gridLayout.addWidget(self.map_subindex_ledit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.loadmap_button = QtWidgets.QPushButton(self.centralwidget)
        self.loadmap_button.setObjectName("loadmap_button")
        self.verticalLayout.addWidget(self.loadmap_button)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.layer1_button = QtWidgets.QPushButton(self.centralwidget)
        self.layer1_button.setEnabled(False)
        self.layer1_button.setObjectName("layer1_button")
        self.verticalLayout.addWidget(self.layer1_button)
        self.layer2_button = QtWidgets.QPushButton(self.centralwidget)
        self.layer2_button.setEnabled(False)
        self.layer2_button.setObjectName("layer2_button")
        self.verticalLayout.addWidget(self.layer2_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.maplayers_tab = QtWidgets.QWidget()
        self.maplayers_tab.setObjectName("maplayers_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.maplayers_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.blocks_view = QtWidgets.QGraphicsView(self.maplayers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocks_view.sizePolicy().hasHeightForWidth())
        self.blocks_view.setSizePolicy(sizePolicy)
        self.blocks_view.setMaximumSize(QtCore.QSize(160, 16777215))
        self.blocks_view.setObjectName("blocks_view")
        self.gridLayout_2.addWidget(self.blocks_view, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.maplayers_tab)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.map_layer_view = QtWidgets.QGraphicsView(self.maplayers_tab)
        self.map_layer_view.setObjectName("map_layer_view")
        self.gridLayout_2.addWidget(self.map_layer_view, 0, 0, 2, 1)
        self.selected_block_ledit = QtWidgets.QLineEdit(self.maplayers_tab)
        self.selected_block_ledit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selected_block_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_block_ledit.setObjectName("selected_block_ledit")
        self.gridLayout_2.addWidget(self.selected_block_ledit, 0, 2, 1, 1)
        self.tabWidget.addTab(self.maplayers_tab, "")
        self.blockeditor_tab = QtWidgets.QWidget()
        self.blockeditor_tab.setObjectName("blockeditor_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.blockeditor_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tileset_view_1 = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileset_view_1.sizePolicy().hasHeightForWidth())
        self.tileset_view_1.setSizePolicy(sizePolicy)
        self.tileset_view_1.setMinimumSize(QtCore.QSize(270, 400))
        self.tileset_view_1.setMaximumSize(QtCore.QSize(288, 400))
        self.tileset_view_1.setObjectName("tileset_view_1")
        self.gridLayout_5.addWidget(self.tileset_view_1, 1, 1, 1, 1)
        self.blocks_view_2 = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocks_view_2.sizePolicy().hasHeightForWidth())
        self.blocks_view_2.setSizePolicy(sizePolicy)
        self.blocks_view_2.setMinimumSize(QtCore.QSize(160, 0))
        self.blocks_view_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.blocks_view_2.setObjectName("blocks_view_2")
        self.gridLayout_5.addWidget(self.blocks_view_2, 0, 0, 3, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_15 = QtWidgets.QLabel(self.blockeditor_tab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 2, 1, 1)
        self.selected_tile_ledit = QtWidgets.QLineEdit(self.blockeditor_tab)
        self.selected_tile_ledit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selected_tile_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_tile_ledit.setObjectName("selected_tile_ledit")
        self.gridLayout_3.addWidget(self.selected_tile_ledit, 2, 3, 1, 1)
        self.palette_combobox = QtWidgets.QComboBox(self.blockeditor_tab)
        self.palette_combobox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.palette_combobox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.palette_combobox.setObjectName("palette_combobox")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.gridLayout_3.addWidget(self.palette_combobox, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.blockeditor_tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 2, 1, 1)
        self.selected_tile_view = QtWidgets.QGraphicsView(self.blockeditor_tab)
        self.selected_tile_view.setMaximumSize(QtCore.QSize(24, 24))
        self.selected_tile_view.setObjectName("selected_tile_view")
        self.gridLayout_3.addWidget(self.selected_tile_view, 1, 0, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.flipX_checkbox = QtWidgets.QCheckBox(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flipX_checkbox.sizePolicy().hasHeightForWidth())
        self.flipX_checkbox.setSizePolicy(sizePolicy)
        self.flipX_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.flipX_checkbox.setObjectName("flipX_checkbox")
        self.gridLayout_4.addWidget(self.flipX_checkbox, 1, 0, 1, 1)
        self.flipY_checkbox = QtWidgets.QCheckBox(self.blockeditor_tab)
        self.flipY_checkbox.setObjectName("flipY_checkbox")
        self.gridLayout_4.addWidget(self.flipY_checkbox, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.selected_block_view = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_block_view.sizePolicy().hasHeightForWidth())
        self.selected_block_view.setSizePolicy(sizePolicy)
        self.selected_block_view.setMaximumSize(QtCore.QSize(48, 48))
        self.selected_block_view.setObjectName("selected_block_view")
        self.horizontalLayout_5.addWidget(self.selected_block_view)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.blockeditor_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 1, 1, 1)
        self.block_behaviours_ledit = QtWidgets.QLineEdit(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.block_behaviours_ledit.sizePolicy().hasHeightForWidth())
        self.block_behaviours_ledit.setSizePolicy(sizePolicy)
        self.block_behaviours_ledit.setMinimumSize(QtCore.QSize(4, 0))
        self.block_behaviours_ledit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.block_behaviours_ledit.setObjectName("block_behaviours_ledit")
        self.gridLayout_4.addWidget(self.block_behaviours_ledit, 2, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 3, 2, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 2, 1, 1, 2)
        self.tileset_view_2 = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileset_view_2.sizePolicy().hasHeightForWidth())
        self.tileset_view_2.setSizePolicy(sizePolicy)
        self.tileset_view_2.setMinimumSize(QtCore.QSize(270, 400))
        self.tileset_view_2.setMaximumSize(QtCore.QSize(288, 400))
        self.tileset_view_2.setObjectName("tileset_view_2")
        self.gridLayout_5.addWidget(self.tileset_view_2, 1, 2, 1, 1)
        self.tabWidget.addTab(self.blockeditor_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem7, 2, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.load_pal_from_img_button = QtWidgets.QPushButton(self.groupBox)
        self.load_pal_from_img_button.setObjectName("load_pal_from_img_button")
        self.gridLayout_7.addWidget(self.load_pal_from_img_button, 1, 0, 1, 2)
        self.palette_combobox2 = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.palette_combobox2.sizePolicy().hasHeightForWidth())
        self.palette_combobox2.setSizePolicy(sizePolicy)
        self.palette_combobox2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.palette_combobox2.setObjectName("palette_combobox2")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.palette_combobox2.addItem("")
        self.gridLayout_7.addWidget(self.palette_combobox2, 0, 1, 1, 1)
        self.palette_image_view = QtWidgets.QGraphicsView(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.palette_image_view.sizePolicy().hasHeightForWidth())
        self.palette_image_view.setSizePolicy(sizePolicy)
        self.palette_image_view.setMinimumSize(QtCore.QSize(272, 80))
        self.palette_image_view.setMaximumSize(QtCore.QSize(272, 80))
        self.palette_image_view.setObjectName("palette_image_view")
        self.gridLayout_7.addWidget(self.palette_image_view, 0, 2, 2, 1)
        self.palette_color_groupbox = QtWidgets.QGroupBox(self.groupBox)
        self.palette_color_groupbox.setObjectName("palette_color_groupbox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.palette_color_groupbox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.blue_spinbox = QtWidgets.QSpinBox(self.palette_color_groupbox)
        self.blue_spinbox.setMaximum(255)
        self.blue_spinbox.setObjectName("blue_spinbox")
        self.gridLayout_9.addWidget(self.blue_spinbox, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.palette_color_groupbox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 1, 0, 1, 1)
        self.red_spinbox = QtWidgets.QSpinBox(self.palette_color_groupbox)
        self.red_spinbox.setMaximum(255)
        self.red_spinbox.setObjectName("red_spinbox")
        self.gridLayout_9.addWidget(self.red_spinbox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.palette_color_groupbox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.palette_color_groupbox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 0, 1, 1)
        self.green_spinbox = QtWidgets.QSpinBox(self.palette_color_groupbox)
        self.green_spinbox.setMaximum(255)
        self.green_spinbox.setObjectName("green_spinbox")
        self.gridLayout_9.addWidget(self.green_spinbox, 1, 1, 1, 1)
        self.save_color_button = QtWidgets.QPushButton(self.palette_color_groupbox)
        self.save_color_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_color_button.sizePolicy().hasHeightForWidth())
        self.save_color_button.setSizePolicy(sizePolicy)
        self.save_color_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.save_color_button.setObjectName("save_color_button")
        self.gridLayout_9.addWidget(self.save_color_button, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.palette_color_groupbox, 0, 3, 2, 1)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 0, 1, 1, 1)
        self.export_tileset_button = QtWidgets.QPushButton(self.groupBox_3)
        self.export_tileset_button.setObjectName("export_tileset_button")
        self.gridLayout_10.addWidget(self.export_tileset_button, 3, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem9, 1, 3, 1, 1)
        self.import_tileset_button = QtWidgets.QPushButton(self.groupBox_3)
        self.import_tileset_button.setObjectName("import_tileset_button")
        self.gridLayout_10.addWidget(self.import_tileset_button, 2, 3, 1, 1)
        self.tileset_num_combobox = QtWidgets.QComboBox(self.groupBox_3)
        self.tileset_num_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.tileset_num_combobox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.tileset_num_combobox.setObjectName("tileset_num_combobox")
        self.tileset_num_combobox.addItem("")
        self.tileset_num_combobox.addItem("")
        self.tileset_num_combobox.addItem("")
        self.gridLayout_10.addWidget(self.tileset_num_combobox, 0, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem10, 0, 3, 1, 1)
        self.change_tileset_view = QtWidgets.QGraphicsView(self.groupBox_3)
        self.change_tileset_view.setMinimumSize(QtCore.QSize(270, 250))
        self.change_tileset_view.setMaximumSize(QtCore.QSize(288, 16777215))
        self.change_tileset_view.setObjectName("change_tileset_view")
        self.gridLayout_10.addWidget(self.change_tileset_view, 0, 0, 5, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuExport = QtWidgets.QMenu(self.menuEdit)
        self.menuExport.setObjectName("menuExport")
        self.menuImport = QtWidgets.QMenu(self.menuEdit)
        self.menuImport.setObjectName("menuImport")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open_Project = QtWidgets.QAction(MainWindow)
        self.action_Open_Project.setObjectName("action_Open_Project")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setEnabled(False)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setEnabled(True)
        self.action_Save.setObjectName("action_Save")
        self.export_map_layer_action = QtWidgets.QAction(MainWindow)
        self.export_map_layer_action.setObjectName("export_map_layer_action")
        self.export_blocks_action = QtWidgets.QAction(MainWindow)
        self.export_blocks_action.setObjectName("export_blocks_action")
        self.export_blocks_behaviour_action = QtWidgets.QAction(MainWindow)
        self.export_blocks_behaviour_action.setObjectName("export_blocks_behaviour_action")
        self.import_map_layer_action = QtWidgets.QAction(MainWindow)
        self.import_map_layer_action.setObjectName("import_map_layer_action")
        self.import_blocks_action = QtWidgets.QAction(MainWindow)
        self.import_blocks_action.setObjectName("import_blocks_action")
        self.import_blocks_behaviour_action = QtWidgets.QAction(MainWindow)
        self.import_blocks_behaviour_action.setObjectName("import_blocks_behaviour_action")
        self.action_New_Project = QtWidgets.QAction(MainWindow)
        self.action_New_Project.setObjectName("action_New_Project")
        self.actionMake = QtWidgets.QAction(MainWindow)
        self.actionMake.setObjectName("actionMake")
        self.actionClean = QtWidgets.QAction(MainWindow)
        self.actionClean.setObjectName("actionClean")
        self.menuFile.addAction(self.action_New_Project)
        self.menuFile.addAction(self.action_Open_Project)
        self.menuFile.addAction(self.action_Save)
        self.menuExport.addAction(self.export_map_layer_action)
        self.menuExport.addAction(self.export_blocks_action)
        self.menuExport.addAction(self.export_blocks_behaviour_action)
        self.menuImport.addAction(self.import_map_layer_action)
        self.menuImport.addAction(self.import_blocks_action)
        self.menuImport.addAction(self.import_blocks_behaviour_action)
        self.menuEdit.addAction(self.menuImport.menuAction())
        self.menuEdit.addAction(self.menuExport.menuAction())
        self.menuProject.addAction(self.actionMake)
        self.menuProject.addAction(self.actionClean)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.map_index_ledit)
        MainWindow.setTabOrder(self.map_index_ledit, self.map_subindex_ledit)
        MainWindow.setTabOrder(self.map_subindex_ledit, self.loadmap_button)
        MainWindow.setTabOrder(self.loadmap_button, self.layer1_button)
        MainWindow.setTabOrder(self.layer1_button, self.layer2_button)
        MainWindow.setTabOrder(self.layer2_button, self.selected_block_ledit)
        MainWindow.setTabOrder(self.selected_block_ledit, self.map_layer_view)
        MainWindow.setTabOrder(self.map_layer_view, self.blocks_view)
        MainWindow.setTabOrder(self.blocks_view, self.blocks_view_2)
        MainWindow.setTabOrder(self.blocks_view_2, self.selected_block_view)
        MainWindow.setTabOrder(self.selected_block_view, self.selected_tile_view)
        MainWindow.setTabOrder(self.selected_tile_view, self.tileset_view_1)
        MainWindow.setTabOrder(self.tileset_view_1, self.tileset_view_2)
        MainWindow.setTabOrder(self.tileset_view_2, self.flipX_checkbox)
        MainWindow.setTabOrder(self.flipX_checkbox, self.flipY_checkbox)
        MainWindow.setTabOrder(self.flipY_checkbox, self.block_behaviours_ledit)
        MainWindow.setTabOrder(self.block_behaviours_ledit, self.palette_combobox)
        MainWindow.setTabOrder(self.palette_combobox, self.selected_tile_ledit)
        MainWindow.setTabOrder(self.selected_tile_ledit, self.palette_combobox2)
        MainWindow.setTabOrder(self.palette_combobox2, self.palette_image_view)
        MainWindow.setTabOrder(self.palette_image_view, self.load_pal_from_img_button)
        MainWindow.setTabOrder(self.load_pal_from_img_button, self.red_spinbox)
        MainWindow.setTabOrder(self.red_spinbox, self.green_spinbox)
        MainWindow.setTabOrder(self.green_spinbox, self.blue_spinbox)
        MainWindow.setTabOrder(self.blue_spinbox, self.save_color_button)
        MainWindow.setTabOrder(self.save_color_button, self.change_tileset_view)
        MainWindow.setTabOrder(self.change_tileset_view, self.tileset_num_combobox)
        MainWindow.setTabOrder(self.tileset_num_combobox, self.import_tileset_button)
        MainWindow.setTabOrder(self.import_tileset_button, self.export_tileset_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MQEQ - Map \"Editor\""))
        self.label.setText(_translate("MainWindow", "Mapdata"))
        self.label_3.setText(_translate("MainWindow", "Subindex"))
        self.label_2.setText(_translate("MainWindow", "Index"))
        self.map_index_ledit.setText(_translate("MainWindow", "0x0"))
        self.map_subindex_ledit.setText(_translate("MainWindow", "0x0"))
        self.loadmap_button.setText(_translate("MainWindow", "Load Map"))
        self.layer1_button.setText(_translate("MainWindow", "Layer 1"))
        self.layer2_button.setText(_translate("MainWindow", "Layer 2"))
        self.label_4.setText(_translate("MainWindow", "Selected block:"))
        self.selected_block_ledit.setText(_translate("MainWindow", "0x0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maplayers_tab), _translate("MainWindow", "Map Layers"))
        self.label_15.setText(_translate("MainWindow", "Palette:"))
        self.selected_tile_ledit.setText(_translate("MainWindow", "0x0"))
        self.palette_combobox.setItemText(0, _translate("MainWindow", "1"))
        self.palette_combobox.setItemText(1, _translate("MainWindow", "2"))
        self.palette_combobox.setItemText(2, _translate("MainWindow", "3"))
        self.palette_combobox.setItemText(3, _translate("MainWindow", "4"))
        self.palette_combobox.setItemText(4, _translate("MainWindow", "5"))
        self.palette_combobox.setItemText(5, _translate("MainWindow", "6"))
        self.palette_combobox.setItemText(6, _translate("MainWindow", "7"))
        self.palette_combobox.setItemText(7, _translate("MainWindow", "8"))
        self.palette_combobox.setItemText(8, _translate("MainWindow", "9"))
        self.palette_combobox.setItemText(9, _translate("MainWindow", "10"))
        self.palette_combobox.setItemText(10, _translate("MainWindow", "11"))
        self.palette_combobox.setItemText(11, _translate("MainWindow", "12"))
        self.palette_combobox.setItemText(12, _translate("MainWindow", "13"))
        self.palette_combobox.setItemText(13, _translate("MainWindow", "14"))
        self.palette_combobox.setItemText(14, _translate("MainWindow", "15"))
        self.palette_combobox.setItemText(15, _translate("MainWindow", "16"))
        self.label_5.setText(_translate("MainWindow", "Selected tile:"))
        self.flipX_checkbox.setText(_translate("MainWindow", "Flip X"))
        self.flipY_checkbox.setText(_translate("MainWindow", "Flip Y"))
        self.label_6.setText(_translate("MainWindow", "Behaviours: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blockeditor_tab), _translate("MainWindow", "Blocks Editor"))
        self.groupBox.setTitle(_translate("MainWindow", "Palette"))
        self.label_7.setText(_translate("MainWindow", "Palette:"))
        self.load_pal_from_img_button.setText(_translate("MainWindow", "Load from image"))
        self.palette_combobox2.setItemText(0, _translate("MainWindow", "1"))
        self.palette_combobox2.setItemText(1, _translate("MainWindow", "2"))
        self.palette_combobox2.setItemText(2, _translate("MainWindow", "3"))
        self.palette_combobox2.setItemText(3, _translate("MainWindow", "4"))
        self.palette_combobox2.setItemText(4, _translate("MainWindow", "5"))
        self.palette_combobox2.setItemText(5, _translate("MainWindow", "6"))
        self.palette_combobox2.setItemText(6, _translate("MainWindow", "7"))
        self.palette_combobox2.setItemText(7, _translate("MainWindow", "8"))
        self.palette_combobox2.setItemText(8, _translate("MainWindow", "9"))
        self.palette_combobox2.setItemText(9, _translate("MainWindow", "10"))
        self.palette_combobox2.setItemText(10, _translate("MainWindow", "11"))
        self.palette_combobox2.setItemText(11, _translate("MainWindow", "12"))
        self.palette_combobox2.setItemText(12, _translate("MainWindow", "13"))
        self.palette_combobox2.setItemText(13, _translate("MainWindow", "14"))
        self.palette_combobox2.setItemText(14, _translate("MainWindow", "15"))
        self.palette_combobox2.setItemText(15, _translate("MainWindow", "16"))
        self.palette_color_groupbox.setTitle(_translate("MainWindow", "Color"))
        self.label_9.setText(_translate("MainWindow", "G:"))
        self.label_8.setText(_translate("MainWindow", "R:"))
        self.label_10.setText(_translate("MainWindow", "B:"))
        self.save_color_button.setText(_translate("MainWindow", "Save"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tileset"))
        self.label_13.setText(_translate("MainWindow", "Tileset:"))
        self.export_tileset_button.setText(_translate("MainWindow", "Export tileset"))
        self.import_tileset_button.setText(_translate("MainWindow", "Import tileset"))
        self.tileset_num_combobox.setItemText(0, _translate("MainWindow", "1"))
        self.tileset_num_combobox.setItemText(1, _translate("MainWindow", "2"))
        self.tileset_num_combobox.setItemText(2, _translate("MainWindow", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tileset editor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.action_Open_Project.setText(_translate("MainWindow", "Open Project"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.action.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.action_Save.setText(_translate("MainWindow", "Save"))
        self.export_map_layer_action.setText(_translate("MainWindow", "Map layer"))
        self.export_blocks_action.setText(_translate("MainWindow", "Blocks"))
        self.export_blocks_behaviour_action.setText(_translate("MainWindow", "Blocks behaviour"))
        self.import_map_layer_action.setText(_translate("MainWindow", "Map layer"))
        self.import_blocks_action.setText(_translate("MainWindow", "Blocks"))
        self.import_blocks_behaviour_action.setText(_translate("MainWindow", "Blocks behaviour"))
        self.action_New_Project.setText(_translate("MainWindow", "New Project"))
        self.actionMake.setText(_translate("MainWindow", "Make"))
        self.actionClean.setText(_translate("MainWindow", "Clean"))

