# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mqeq.ui'
#
# Created: Thu Mar 30 17:56:04 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.map_index_ledit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_index_ledit.sizePolicy().hasHeightForWidth())
        self.map_index_ledit.setSizePolicy(sizePolicy)
        self.map_index_ledit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.map_index_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.map_index_ledit.setObjectName("map_index_ledit")
        self.gridLayout.addWidget(self.map_index_ledit, 0, 1, 1, 1)
        self.map_subindex_ledit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_subindex_ledit.sizePolicy().hasHeightForWidth())
        self.map_subindex_ledit.setSizePolicy(sizePolicy)
        self.map_subindex_ledit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.map_subindex_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.map_subindex_ledit.setObjectName("map_subindex_ledit")
        self.gridLayout.addWidget(self.map_subindex_ledit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.loadmap_button = QtWidgets.QPushButton(self.centralwidget)
        self.loadmap_button.setObjectName("loadmap_button")
        self.verticalLayout.addWidget(self.loadmap_button)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.layer1_button = QtWidgets.QPushButton(self.centralwidget)
        self.layer1_button.setEnabled(False)
        self.layer1_button.setObjectName("layer1_button")
        self.verticalLayout.addWidget(self.layer1_button)
        self.layer2_button = QtWidgets.QPushButton(self.centralwidget)
        self.layer2_button.setEnabled(False)
        self.layer2_button.setObjectName("layer2_button")
        self.verticalLayout.addWidget(self.layer2_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.maplayers_tab = QtWidgets.QWidget()
        self.maplayers_tab.setObjectName("maplayers_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.maplayers_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.blocks_view = QtWidgets.QGraphicsView(self.maplayers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocks_view.sizePolicy().hasHeightForWidth())
        self.blocks_view.setSizePolicy(sizePolicy)
        self.blocks_view.setMaximumSize(QtCore.QSize(160, 16777215))
        self.blocks_view.setObjectName("blocks_view")
        self.gridLayout_2.addWidget(self.blocks_view, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.maplayers_tab)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.map_layer_view = QtWidgets.QGraphicsView(self.maplayers_tab)
        self.map_layer_view.setObjectName("map_layer_view")
        self.gridLayout_2.addWidget(self.map_layer_view, 0, 0, 2, 1)
        self.selected_block_ledit = QtWidgets.QLineEdit(self.maplayers_tab)
        self.selected_block_ledit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selected_block_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_block_ledit.setObjectName("selected_block_ledit")
        self.gridLayout_2.addWidget(self.selected_block_ledit, 0, 2, 1, 1)
        self.tabWidget.addTab(self.maplayers_tab, "")
        self.blockeditor_tab = QtWidgets.QWidget()
        self.blockeditor_tab.setObjectName("blockeditor_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.blockeditor_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.blocks_view_2 = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocks_view_2.sizePolicy().hasHeightForWidth())
        self.blocks_view_2.setSizePolicy(sizePolicy)
        self.blocks_view_2.setMinimumSize(QtCore.QSize(160, 0))
        self.blocks_view_2.setMaximumSize(QtCore.QSize(160, 16777215))
        self.blocks_view_2.setObjectName("blocks_view_2")
        self.gridLayout_5.addWidget(self.blocks_view_2, 0, 0, 6, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.selected_block_view = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_block_view.sizePolicy().hasHeightForWidth())
        self.selected_block_view.setSizePolicy(sizePolicy)
        self.selected_block_view.setMaximumSize(QtCore.QSize(48, 48))
        self.selected_block_view.setObjectName("selected_block_view")
        self.horizontalLayout_5.addWidget(self.selected_block_view)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.flipX_checkbox = QtWidgets.QCheckBox(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flipX_checkbox.sizePolicy().hasHeightForWidth())
        self.flipX_checkbox.setSizePolicy(sizePolicy)
        self.flipX_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.flipX_checkbox.setObjectName("flipX_checkbox")
        self.gridLayout_4.addWidget(self.flipX_checkbox, 1, 0, 1, 1)
        self.flipY_checkbox = QtWidgets.QCheckBox(self.blockeditor_tab)
        self.flipY_checkbox.setObjectName("flipY_checkbox")
        self.gridLayout_4.addWidget(self.flipY_checkbox, 2, 0, 1, 1)
        self.selected_tile_view = QtWidgets.QGraphicsView(self.blockeditor_tab)
        self.selected_tile_view.setMaximumSize(QtCore.QSize(24, 24))
        self.selected_tile_view.setObjectName("selected_tile_view")
        self.gridLayout_4.addWidget(self.selected_tile_view, 1, 1, 2, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_15 = QtWidgets.QLabel(self.blockeditor_tab)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_2.addWidget(self.label_15)
        self.palette_combobox = QtWidgets.QComboBox(self.blockeditor_tab)
        self.palette_combobox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.palette_combobox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.palette_combobox.setObjectName("palette_combobox")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.palette_combobox.addItem("")
        self.horizontalLayout_2.addWidget(self.palette_combobox)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 4, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(self.blockeditor_tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.selected_tile_ledit = QtWidgets.QLineEdit(self.blockeditor_tab)
        self.selected_tile_ledit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.selected_tile_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_tile_ledit.setObjectName("selected_tile_ledit")
        self.horizontalLayout_3.addWidget(self.selected_tile_ledit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tileset_view_1 = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileset_view_1.sizePolicy().hasHeightForWidth())
        self.tileset_view_1.setSizePolicy(sizePolicy)
        self.tileset_view_1.setMinimumSize(QtCore.QSize(288, 160))
        self.tileset_view_1.setMaximumSize(QtCore.QSize(288, 160))
        self.tileset_view_1.setObjectName("tileset_view_1")
        self.verticalLayout_3.addWidget(self.tileset_view_1)
        self.tileset_view_2 = QtWidgets.QGraphicsView(self.blockeditor_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tileset_view_2.sizePolicy().hasHeightForWidth())
        self.tileset_view_2.setSizePolicy(sizePolicy)
        self.tileset_view_2.setMinimumSize(QtCore.QSize(288, 160))
        self.tileset_view_2.setMaximumSize(QtCore.QSize(288, 160))
        self.tileset_view_2.setObjectName("tileset_view_2")
        self.verticalLayout_3.addWidget(self.tileset_view_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 1, 2, 4, 1)
        self.tabWidget.addTab(self.blockeditor_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open_ROM = QtWidgets.QAction(MainWindow)
        self.action_Open_ROM.setObjectName("action_Open_ROM")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setEnabled(False)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setEnabled(False)
        self.action_Save.setObjectName("action_Save")
        self.menuFile.addAction(self.action_Open_ROM)
        self.menuFile.addAction(self.action_Save)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MQEQ - Map \"Editor\""))
        self.label.setText(_translate("MainWindow", "Mapdata"))
        self.label_3.setText(_translate("MainWindow", "Subindex"))
        self.label_2.setText(_translate("MainWindow", "Index"))
        self.map_index_ledit.setText(_translate("MainWindow", "0x0"))
        self.map_subindex_ledit.setText(_translate("MainWindow", "0x0"))
        self.loadmap_button.setText(_translate("MainWindow", "Load Map"))
        self.layer1_button.setText(_translate("MainWindow", "Layer 1"))
        self.layer2_button.setText(_translate("MainWindow", "Layer 2"))
        self.label_4.setText(_translate("MainWindow", "Selected block:"))
        self.selected_block_ledit.setText(_translate("MainWindow", "0x0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.maplayers_tab), _translate("MainWindow", "Map Layers"))
        self.flipX_checkbox.setText(_translate("MainWindow", "Flip X"))
        self.flipY_checkbox.setText(_translate("MainWindow", "Flip Y"))
        self.label_15.setText(_translate("MainWindow", "Palette"))
        self.palette_combobox.setItemText(0, _translate("MainWindow", "1"))
        self.palette_combobox.setItemText(1, _translate("MainWindow", "2"))
        self.palette_combobox.setItemText(2, _translate("MainWindow", "3"))
        self.palette_combobox.setItemText(3, _translate("MainWindow", "4"))
        self.palette_combobox.setItemText(4, _translate("MainWindow", "5"))
        self.palette_combobox.setItemText(5, _translate("MainWindow", "6"))
        self.palette_combobox.setItemText(6, _translate("MainWindow", "7"))
        self.palette_combobox.setItemText(7, _translate("MainWindow", "8"))
        self.palette_combobox.setItemText(8, _translate("MainWindow", "9"))
        self.palette_combobox.setItemText(9, _translate("MainWindow", "10"))
        self.palette_combobox.setItemText(10, _translate("MainWindow", "11"))
        self.palette_combobox.setItemText(11, _translate("MainWindow", "12"))
        self.palette_combobox.setItemText(12, _translate("MainWindow", "13"))
        self.palette_combobox.setItemText(13, _translate("MainWindow", "14"))
        self.palette_combobox.setItemText(14, _translate("MainWindow", "15"))
        self.palette_combobox.setItemText(15, _translate("MainWindow", "16"))
        self.label_5.setText(_translate("MainWindow", "Selected tile:"))
        self.selected_tile_ledit.setText(_translate("MainWindow", "0x0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blockeditor_tab), _translate("MainWindow", "Blocks Editor"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_Open_ROM.setText(_translate("MainWindow", "Open ROM"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.action.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.action_Save.setText(_translate("MainWindow", "Save"))

