# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mqeq.ui'
#
# Created: Mon Mar 27 14:30:43 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/mqeq-icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(False)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.map_index_ledit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_index_ledit.sizePolicy().hasHeightForWidth())
        self.map_index_ledit.setSizePolicy(sizePolicy)
        self.map_index_ledit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.map_index_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.map_index_ledit.setObjectName("map_index_ledit")
        self.gridLayout.addWidget(self.map_index_ledit, 0, 1, 1, 1)
        self.map_subindex_ledit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_subindex_ledit.sizePolicy().hasHeightForWidth())
        self.map_subindex_ledit.setSizePolicy(sizePolicy)
        self.map_subindex_ledit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.map_subindex_ledit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.map_subindex_ledit.setObjectName("map_subindex_ledit")
        self.gridLayout.addWidget(self.map_subindex_ledit, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.loadmap_button = QtWidgets.QPushButton(self.centralwidget)
        self.loadmap_button.setObjectName("loadmap_button")
        self.verticalLayout.addWidget(self.loadmap_button)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.layer1_button = QtWidgets.QPushButton(self.centralwidget)
        self.layer1_button.setEnabled(False)
        self.layer1_button.setObjectName("layer1_button")
        self.verticalLayout.addWidget(self.layer1_button)
        self.layer2_button = QtWidgets.QPushButton(self.centralwidget)
        self.layer2_button.setEnabled(False)
        self.layer2_button.setObjectName("layer2_button")
        self.verticalLayout.addWidget(self.layer2_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectedblock_label = QtWidgets.QLabel(self.tab)
        self.selectedblock_label.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedblock_label.setObjectName("selectedblock_label")
        self.gridLayout_2.addWidget(self.selectedblock_label, 0, 2, 1, 1)
        self.blocks_view = QtWidgets.QGraphicsView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blocks_view.sizePolicy().hasHeightForWidth())
        self.blocks_view.setSizePolicy(sizePolicy)
        self.blocks_view.setMaximumSize(QtCore.QSize(160, 16777215))
        self.blocks_view.setObjectName("blocks_view")
        self.gridLayout_2.addWidget(self.blocks_view, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.map_layer_view = QtWidgets.QGraphicsView(self.tab)
        self.map_layer_view.setObjectName("map_layer_view")
        self.gridLayout_2.addWidget(self.map_layer_view, 0, 0, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.tilenum_label = QtWidgets.QLabel(self.groupBox)
        self.tilenum_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tilenum_label.setObjectName("tilenum_label")
        self.gridLayout_3.addWidget(self.tilenum_label, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.blockpart_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.blockpart_spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.blockpart_spinBox.setMaximum(3)
        self.blockpart_spinBox.setObjectName("blockpart_spinBox")
        self.gridLayout_3.addWidget(self.blockpart_spinBox, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.palettenum_label = QtWidgets.QLabel(self.groupBox)
        self.palettenum_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.palettenum_label.setObjectName("palettenum_label")
        self.gridLayout_3.addWidget(self.palettenum_label, 4, 1, 1, 1)
        self.flipx_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.flipx_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.flipx_checkBox.setText("")
        self.flipx_checkBox.setCheckable(False)
        self.flipx_checkBox.setObjectName("flipx_checkBox")
        self.gridLayout_3.addWidget(self.flipx_checkBox, 2, 1, 1, 1)
        self.flipy_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.flipy_checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.flipy_checkBox.setText("")
        self.flipy_checkBox.setCheckable(False)
        self.flipy_checkBox.setObjectName("flipy_checkBox")
        self.gridLayout_3.addWidget(self.flipy_checkBox, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 1, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_ROM = QtWidgets.QAction(MainWindow)
        self.actionOpen_ROM.setObjectName("actionOpen_ROM")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen_ROM)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MQEQ - Map \"Editor\""))
        self.label.setText(_translate("MainWindow", "Mapdata"))
        self.label_3.setText(_translate("MainWindow", "Subindex"))
        self.label_2.setText(_translate("MainWindow", "Index"))
        self.map_index_ledit.setText(_translate("MainWindow", "0x0"))
        self.map_subindex_ledit.setText(_translate("MainWindow", "0x0"))
        self.loadmap_button.setText(_translate("MainWindow", "Load Map"))
        self.layer1_button.setText(_translate("MainWindow", "Layer 1"))
        self.layer2_button.setText(_translate("MainWindow", "Layer 2"))
        self.selectedblock_label.setText(_translate("MainWindow", "0x0"))
        self.label_4.setText(_translate("MainWindow", "Selected block:"))
        self.groupBox.setTitle(_translate("MainWindow", "Block data:"))
        self.label_7.setText(_translate("MainWindow", "Flip x"))
        self.label_8.setText(_translate("MainWindow", "Flip y"))
        self.tilenum_label.setText(_translate("MainWindow", "0x0"))
        self.label_5.setText(_translate("MainWindow", "Tile:"))
        self.label_9.setText(_translate("MainWindow", "Palette:"))
        self.palettenum_label.setText(_translate("MainWindow", "0x0"))
        self.label_6.setText(_translate("MainWindow", "Block part:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Map Layers"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_ROM.setText(_translate("MainWindow", "Open ROM"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

